language: csharp
solution: Springboard365.Xrm.Plugins.Core.sln
install:
  - nuget restore Springboard365.Xrm.Plugins.Core.sln
  - nuget install NUnit.ConsoleRunner -Version 3.4.1 -ExcludeVersion -OutputDirectory tools
  - nuget install Springboard365.Tools.DynamicsCrm.ImportCustomizations -PreRelease -ExcludeVersion -OutputDirectory tools
script:
  - echo -e "<?xml version=\"1.0\" encoding=\"utf-8\"?><configuration><appSettings><add key=\"CrmUrl\" value=\"$dynamics_crm_url\"/><add key=\"CrmUserName\" value=\"$dynamics_crm_username\"/><add key=\"CrmPassword\" value=\"$dynamics_crm_password\"/><add key=\"Tenant\" value=\"$dynamics_crm_tenant\"/><add key=\"ClientId\" value=\"$dynamics_crm_client_id\"/><add key=\"ClientSecret\" value=\"$dynamics_crm_client_secret\"/><add key=\"Platform\" value=\"web\"/></appSettings></configuration>" > ./Springboard365.Xrm.Plugins.Core.IntegrationTest/App.config
  - nuget restore Springboard365.Xrm.Plugins.Core.IntegrationTest.sln
  - xbuild Springboard365.Xrm.Plugins.Core.IntegrationTest.sln /p:Configuration=Release;TargetFrameworkProfile="";TargetFrameworkVersion=4.5
  - mono ./tools/NUnit.ConsoleRunner/tools/nunit3-console.exe ./Springboard365.Xrm.Plugins.Core.IntegrationTest/bin/Release/Springboard365.Xrm.Plugins.Core.IntegrationTest.dll  --work=./TestResult/Integration/Net45
  - echo "Finished"